version: '3.8'

services:
  frontend:
    # Имя образа для вашего React-приложения
    image: my-react-app:latest
    # Указывает, что образ нужно собрать из Dockerfile в текущем контексте
    build:
      context: . # Точка контекста сборки - текущая директория
      dockerfile: Dockerfile # Имя файла Dockerfile
    # Публикует порт 80 контейнера на порт 3000 хоста
    # Теперь вы можете открыть http://localhost:3000 в браузере
    ports:
      - "3000:80"
    # Перезапуск контейнера при сбоях
    restart: unless-stopped

# volumes: # Не требуется для статического React-приложения
# networks: # Не требуется для базового запуска